"""Developer Kit (TASK-047, M8-E5).

``DevKit.create_scaffold`` generates a starter plugin/agent/capability/tool/
workflow package: aios.plugin.yaml + src/<name>/ + tests/ + README.md +
pyproject.toml. Deterministic output (no timestamps), never overwrites
existing files, and the generated stubs are importable Python.
"""

from __future__ import annotations

import re
from pathlib import Path

from .errors import DevKitError

_KIND_MAP = {
    "plugin": {"manifest_kind": "integration", "class_name": "IntegrationPlugin",
               "base": "Tool", "base_id": "tool"},
    "agent": {"manifest_kind": "agent", "class_name": "MyAgent", "base": "Agent",
              "base_id": "agent"},
    "capability": {"manifest_kind": "capability", "class_name": "MyCapability",
                   "base": "Capability", "base_id": "capability"},
    "tool": {"manifest_kind": "tool", "class_name": "MyTool", "base": "Tool",
             "base_id": "tool"},
    "workflow": {"manifest_kind": "workflow", "class_name": "MyWorkflow",
                 "base": "Workflow", "base_id": "workflow"},
}

_NAME_RE = re.compile(r"^[a-z][a-z0-9_]*$")

_MANIFEST_TEMPLATE = """\
id: {name}.{kind}
name: {title}
version: 0.1.0
aios:
  min: 1.0.0
  max: 2.x
plugin_type: {manifest_kind}
provides:
  - kind: {manifest_kind}
    id: {name}.{kind}
permissions:
  - {kind}.read
dependencies: []
description: "{title} plugin scaffold"
"""

_PLUGIN_TEMPLATE = """\
\"\"\"{title} — generated by AIOS Developer Kit.

TODO: implement the component below using the public AIOS SDK.
\"\"\"

from aios import {base} as {base_import}


class {class_name}({base}):
    id = "{name}.{kind}"
    capabilities = ("{name}.{kind}",)

    def run(self, input):  # noqa: A002 — SDK boundary signature
        raise NotImplementedError("TODO: implement run()")
"""

_AGENT_TEMPLATE = """\
\"\"\"{title} — generated by AIOS Developer Kit.

TODO: implement the agent using the public AIOS SDK.
\"\"\"

from aios import Agent, AgentRequest, AgentResponse


class {class_name}(Agent):
    id = "{name}.{kind}"
    capabilities = ("{name}.{kind}",)

    def handle(self, request: AgentRequest) -> AgentResponse:
        return AgentResponse("TODO: handle " + repr(request.input))
"""

_TEST_TEMPLATE = """\
import pytest


def test_scaffold_imports():
    \"\"\"Stub test — replace with real behavior tests.\"\"\"
    assert True
"""

_README_TEMPLATE = """\
# {title}

Generated by the AIOS Developer Kit.

## Quickstart

Install the SDK, then run:

    pytest

The stub raises `NotImplementedError` until you implement `run()`.
"""

_PYPROJECT_TEMPLATE = """\
[project]
name = "{name}-{kind}"
version = "0.1.0"
requires-python = ">=3.10"
"""


class DevKit:
    """Stateless scaffold generator."""

    def create_scaffold(self, kind: str, name: str, out_dir: Path | str) -> list[str]:
        if kind not in _KIND_MAP:
            raise DevKitError(f"unknown kind {kind!r}; expected one of {sorted(_KIND_MAP)}")
        if not _NAME_RE.match(name):
            raise DevKitError(f"invalid name {name!r}; use [a-z][a-z0-9_]*")
        info = _KIND_MAP[kind]
        root = Path(out_dir) / name
        created: list[str] = []

        files = {
            "aios.plugin.yaml": _MANIFEST_TEMPLATE.format(
                name=name, kind=kind, title=name.replace("_", " ").title(),
                manifest_kind=info["manifest_kind"],
            ),
            "README.md": _README_TEMPLATE.format(title=name.replace("_", " ").title()),
            "pyproject.toml": _PYPROJECT_TEMPLATE.format(name=name, kind=kind),
        }
        if kind == "agent":
            stub = _AGENT_TEMPLATE.format(
                name=name, kind=kind, class_name=info["class_name"],
                title=name.replace("_", " ").title(),
            )
        else:
            stub = _PLUGIN_TEMPLATE.format(
                name=name, kind=kind, class_name=info["class_name"],
                base=info["base"], base_import=info["base"],
                title=name.replace("_", " ").title(),
            )
        files[f"src/{name}/plugin.py"] = stub
        files["tests/test_scaffold.py"] = _TEST_TEMPLATE
        files["src/__init__.py"] = ""

        for rel, content in files.items():
            target = root / rel
            if target.exists():
                raise DevKitError(f"refusing to overwrite existing file: {target}")
        for rel, content in files.items():
            target = root / rel
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8")
            created.append(str(target))
        return created


__all__ = ["DevKit"]
